import * as React from 'react';
import type { Metadata } from 'next'
import './globals.css'
import { CssVarsProvider } from '@mui/joy'
import theme from '@/components/theme'
import PanelLayout from '@/components/layout/panel'
import { UserProvider } from '@/context/User'
import { UIProvider } from '@/context/UI'
import NextTopLoader from 'nextjs-toploader';

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="fa" dir='rtl'>
      <body>
        <UIProvider>
          <UserProvider>
            <CssVarsProvider theme={theme}>
              <div dir='ltr'>
                <NextTopLoader
                  color="#0B6BCB"
                  initialPosition={0.08}
                  crawlSpeed={200}
                  height={4}
                  crawl={true}
                  showSpinner={true}
                  easing="ease"
                  speed={200}
                  shadow="0 0 10px #0B6BCB,0 0 5px #0B6BCB"
                />
              </div>
              <PanelLayout>{children}</PanelLayout>
            </CssVarsProvider>
          </UserProvider>
        </UIProvider>
      </body>
    </html>
  )
}
