import * as React from 'react';
import type { Metadata } from 'next'
import './globals.css'
import { CssVarsProvider } from '@mui/joy'
import theme from '@/components/theme'
import PanelLayout from '@/components/layout/panel'
import { UserProvider } from '@/context/User'
import { UIProvider } from '@/context/UI'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="fa" dir='rtl'>
      <body>
        <UIProvider>
          <UserProvider>
            <CssVarsProvider theme={theme}>
              <PanelLayout>{children}</PanelLayout>
            </CssVarsProvider>
          </UserProvider>
        </UIProvider>
      </body>
    </html>
  )
}
